"""rating-added-to-vendor

Revision ID: 1d0dabec7e6c
Revises: 2ca2cfb4d52a
Create Date: 2025-11-13 16:54:11.199086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0dabec7e6c'
down_revision: Union[str, Sequence[str], None] = '2ca2cfb4d52a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
