"""Initial clean migration

Revision ID: 2ca2cfb4d52a
Revises: 
Create Date: 2025-11-13 16:30:45.396048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca2cfb4d52a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cart_items', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'carts', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'item_addon_group_association', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.add_column('item_addon_groups', sa.Column('vendor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'item_addon_groups', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('item_addon_groups', 'item_id')
    op.create_foreign_key(None, 'item_variations', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'items', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_items', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vendor_wallets', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendor_wallets', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'item_variations', type_='foreignkey')
    op.add_column('item_addon_groups', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'item_addon_groups', type_='foreignkey')
    op.drop_column('item_addon_groups', 'vendor_id')
    op.drop_constraint(None, 'item_addon_group_association', type_='foreignkey')
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    # ### end Alembic commands ###
