"""add-imageurl-to-itemaddon

Revision ID: 72f004606f97
Revises: 1d0dabec7e6c
Create Date: 2025-11-13 18:53:18.140503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f004606f97'
down_revision: Union[str, Sequence[str], None] = '1d0dabec7e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_addons', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_addons', 'image_url')
    # ### end Alembic commands ###
