"""add order_items_association table

Revision ID: c82af99b62de
Revises: cd8ddc661485
Create Date: 2025-11-17 22:26:37.958550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82af99b62de'
down_revision: Union[str, Sequence[str], None] = 'cd8ddc661485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cart_item_addons', 'item_addons', ['addon_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cart_items', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'item_addon_group_association', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'item_variations', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.add_column('items', sa.Column('quantity', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_item_addons', 'order_items', ['order_item_id'], ['id'], ondelete='CASCADE')
    op.add_column('order_items', sa.Column('variation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'item_variations', ['variation_id'], ['id'], ondelete='SET NULL')
    op.drop_column('order_tracking', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_tracking', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'variation_id')
    op.drop_constraint(None, 'order_item_addons', type_='foreignkey')
    op.drop_column('items', 'quantity')
    op.drop_constraint(None, 'item_variations', type_='foreignkey')
    op.drop_constraint(None, 'item_addon_group_association', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint(None, 'cart_item_addons', type_='foreignkey')
    # ### end Alembic commands ###
