"""addon group ids added to table

Revision ID: c9873e3e3071
Revises: 19bb4998c9cc
Create Date: 2025-11-14 10:17:56.032364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9873e3e3071'
down_revision: Union[str, Sequence[str], None] = '19bb4998c9cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('addon_group_ids', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'addon_group_ids')
    # ### end Alembic commands ###
