"""item delete and update fix

Revision ID: cd8ddc661485
Revises: dc38e46a7f62
Create Date: 2025-11-14 13:47:10.049789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd8ddc661485'
down_revision: Union[str, Sequence[str], None] = 'dc38e46a7f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cart_items', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.add_column('delivery_addresses', sa.Column('name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'item_addon_group_association', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'item_variations', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_items', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'item_variations', type_='foreignkey')
    op.drop_constraint(None, 'item_addon_group_association', type_='foreignkey')
    op.drop_column('delivery_addresses', 'name')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    # ### end Alembic commands ###
